name: Cypress Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm  # Enable caching for faster npm install

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PLATFORM_URL: https://vcst-qa-storefront.govirto.com
          CYPRESS_BASE_URL: https://vcst-qa.govirto.com
          CYPRESS_ADMIN_NAME: ${{ secrets.ADMIN_NAME }}
          CYPRESS_ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          CYPRESS_API_KEY: ${{ secrets.API_KEY }}
          CYPRESS_ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          CYPRESS_LOGIN_CORP_EMAIL: ${{ secrets.LOGIN_CORP_EMAIL }}
          CYPRESS_LOGIN_CORP_PASSWORD: ${{ secrets.LOGIN_CORP_PASSWORD }}
          CYPRESS_CARD_NUMBER_VISA: ${{ secrets.CARD_NUMBER_VISA }}
          CYPRESS_CVV: ${{ secrets.CVV }}

